version: '2'

services:
  poll-server:
    build: .
    ports:
      - "3031:80"
    environment:
      POSTGRES_ADDRESS: database:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./client/public:/app/public
    links:
      - database
    depends_on: 
      - database

  database:
    image: postgres:latest
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD